# Generated by Django 5.1.5 on 2025-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.FileField(upload_to='company_logos/')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('year_of_experience', models.IntegerField(choices=[(10, '10 years'), (11, '11 years'), (12, '12 years'), (13, '13 years'), (14, '14 years'), (15, '15 years')])),
                ('joining_date', models.DateField()),
                ('packages', models.IntegerField()),
                ('number_of_positions', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('posted_by', models.IntegerField()),
                ('skills', models.ManyToManyField(to='jobboard.skill')),
            ],
        ),
    ]
