# Generated by Django 5.1.5 on 2025-02-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='company_logo',
            field=models.URLField(max_length=255),
        ),
    ]
